# Generated by Django 5.0.1 on 2024-01-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiccontainer',
            name='imagesrc',
        ),
    ]
